// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  hero: dynamic(() => import("./Hero")),
  tech_stack: dynamic(() => import("./TechStack")),
};
